nohup python -m ocec train \
--data_root data/dataset.parquet \
--output_dir runs/ocec \
--epochs 5000 \
--batch_size 512 \
--num_workers 8 \
--train_ratio 0.8 \
--val_ratio 0.2 \
--image_size 32x96 \
--base_channels 32 \
--num_blocks 4 \
--arch_variant baseline \
--seed 42 \
--device auto \
--use_amp > logs/train_$(date +%Y%m%d_%H%M%S).log 2>&1 &